project:
  type: website
  output-dir: _site

website:
  title: "Diego G. Campos"
  description: "Associate Professor | Knowledge Centre for Education, University of Stavanger"
  site-url: https://www.diegocampos.co
  favicon: assets/favicon.ico

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: presentations.qmd
        text: Presentations
      - href: teaching.qmd
        text: Teaching
      - href: supervision.qmd
        text: Supervision
      - href: grants.qmd
        text: Awards & Grants
      - href: service.qmd
        text: Service

  page-footer:
    left: "© Diego G. Campos"
    right: |
      <a href="mailto:diego.a.campos@uis.no" class="footer-icon" title="Email"><i class="fas fa-envelope"></i></a>
      <a href="https://scholar.google.com/citations?user=TUdYbvwAAAAJ&hl=en" class="footer-icon" title="Google Scholar" target="_blank"><i class="ai ai-google-scholar"></i></a>
      <a href="https://orcid.org/0000-0002-8820-5881" class="footer-icon" title="ORCID" target="_blank"><i class="ai ai-orcid"></i></a>
      <a href="https://osf.io/f2nct/" class="footer-icon" title="OSF" target="_blank"><i class="ai ai-osf"></i></a>
      <a href="https://github.com/diegc15" class="footer-icon" title="GitHub" target="_blank"><i class="fab fa-github"></i></a>
      <a href="https://www.linkedin.com/in/diego-g-campos-phd-55844872" class="footer-icon" title="LinkedIn" target="_blank"><i class="fab fa-linkedin-in"></i></a>
      <a href="https://bsky.app/profile/diegc.bsky.social" class="footer-icon" title="Bluesky" target="_blank"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" width="13" height="13" fill="currentColor"><path d="M407.8 294.7c-3.3-.4-6.7-.8-10-1.3c3.4 .4 6.7 .9 10 1.3zM288 227.1C261.9 176.4 190.9 81.9 124.9 35.3C61.3-9.7 0 17 0 80.6c0 80.4 74.4 68.1 74.4 74.5C74.4 196.2 51.6 302.4 .7 379.4C0 380.3 0 381.2 0 382.1C0 435 28.8 448 55.4 448c41.7 0 59-22.6 70.4-37.9L220 271.3c0 0-16.9 97-42.8 158.3c-5.2 12.3-1.7 26.6 8.8 35.4c10.5 8.8 25.3 10.2 37.1 3.4l109.2-63.6C344.5 424 367.3 448 409 448c26.6 0 55.4-13 55.4-65.9c0-.9 0-1.8-.7-2.7c-50.9-77-73.7-183.2-73.7-224.5c0-6.4 74.4 5.9 74.4-74.5c0-63.5-61.3-90.3-124.9-44.9c-66 46.6-137 141.1-163.1 191.8c-3.5 6.8-6.8 13.7-9.7 20.8H288z"/></svg></a>

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    link-external-newwindow: true
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.9.4/css/academicons.min.css">

execute:
  freeze: auto
